"""Recursive tree-based deep research with planning, supervision, and critique."""

from __future__ import annotations

import json
import logging
import re
from collections.abc import Callable
from dataclasses import dataclass, field
from typing import Any

import httpx

logger = logging.getLogger("aiw.deep_search")

# ── Lazy crewAI ────────────────────────────────────────────
# crewAI is optional (pip install "ai-workspace[crewai]").
# These lazy globals are set on first use.
_Agent = None
_Crew = None
_Task = None
_LLM = None


def _ensure_crewai():
    """Import crewAI lazily. Raises ImportError if not installed."""
    global _Agent, _Crew, _Task, _LLM
    if _Agent is None:
        from crewai import Agent as _AgentCls  # type: ignore[import-untyped]
        from crewai import Crew as _CrewCls
        from crewai import Task as _TaskCls
        from crewai.llm import LLM as _LLMCls
        _Agent = _AgentCls
        _Crew = _CrewCls
        _Task = _TaskCls
        _LLM = _LLMCls


from pydantic import BaseModel, Field


class PlanOutput(BaseModel):
    """Output model for the planning step — list of sub-questions."""
    questions: list[str] = Field(
        default_factory=list,
        description="List of sub-questions to research"
    )


class ResearchAnswer(BaseModel):
    """Output model for answering a sub-question."""
    answer: str = Field(description="Detailed answer to the question")
    confidence: float = Field(
        default=0.5, ge=0.0, le=1.0,
        description="Confidence in the answer (0.0 to 1.0)"
    )
    sources: list[str] = Field(
        default_factory=list,
        description="Sources used to answer (URLs or references)"
    )
    further_questions: list[str] = Field(
        default_factory=list,
        description="Sub-questions that need deeper research"
    )


class SynthesisReport(BaseModel):
    """Output model for the final synthesis step."""
    summary: str = Field(description="Executive summary (2-3 sentences)")
    key_findings: list[str] = Field(
        default_factory=list,
        description="Key findings as bullet points"
    )
    detailed_analysis: str = Field(
        default="",
        description="Full detailed analysis text"
    )
    confidence: float = Field(
        default=0.5, ge=0.0, le=1.0,
        description="Overall confidence in the research"
    )
    sources: list[str] = Field(
        default_factory=list,
        description="All sources used across the research"
    )




def guardrail_min_confidence(output, min_confidence: float = 0.3):
    """Guardrail: reject answers with unreasonably low confidence.

    Usage:
        task = _Task(..., guardrail=lambda o: guardrail_min_confidence(o, 0.4))
    """
    if hasattr(output, 'pydantic') and output.pydantic:
        model = output.pydantic
        if hasattr(model, 'confidence') and model.confidence < min_confidence:
            return (False, f"Confidence {model.confidence:.0%} is below minimum {min_confidence:.0%}. Research more.")
    elif hasattr(output, 'raw') and output.raw:
        # Fallback: check raw text for confidence markers
        text = str(output.raw).lower()
        if any(marker in text for marker in ("uncertain", "unclear", "cannot determine", "unknown")):
            return (False, "Answer shows high uncertainty. Research deeper.")
    return (True, output)


@dataclass
class SubQuestion:
    """A sub-question generated by the planner."""
    question: str
    context: str = ""
    answer: str = ""
    sources: list[str] = field(default_factory=list)
    confidence: float = 0.0


@dataclass
class ResearchResult:
    """Complete research result."""
    original_query: str
    sub_questions: list[SubQuestion] = field(default_factory=list)
    summary: str = ""
    detailed_report: str = ""
    sources: list[str] = field(default_factory=list)
    confidence: float = 0.0


def _safe_float(value: Any, default: float = 0.0) -> float:
    """Coerce a value to float, handling strings and None."""
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return float(value)
    if isinstance(value, str):
        try:
            return float(value)
        except ValueError:
            pass
    return default


def _parse_json_safe(text: str) -> Any:
    """Parse JSON from text, handling markdown code blocks and extra whitespace."""
    text = text.strip()
    # Strip ```json ... ``` or ``` ... ``` wrapping
    if text.startswith("```"):
        lines = text.split("\n")
        if lines[0].startswith("```"):
            lines = lines[1:]  # Remove opening fence
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]  # Remove closing fence
        text = "\n".join(lines).strip()
    # Try parsing
    try:
        return json.loads(text)
    except (json.JSONDecodeError, ValueError):
        # Try to find a JSON array/object in the text
        match = re.search(r'\[.*\]', text, re.DOTALL)
        if match:
            try:
                return json.loads(match.group())
            except (json.JSONDecodeError, ValueError):
                pass
        match = re.search(r'\{.*\}', text, re.DOTALL)
        if match:
            try:
                return json.loads(match.group())
            except (json.JSONDecodeError, ValueError):
                pass
        raise ValueError(f"Could not parse JSON from: {text[:200]}")


class DeepSearchEngine:
    """Recursive deep search using local LLMs + optional web search."""

    def __init__(
        self,
        model: str = "ollama/qwen3:14b",
        deep_model: str = "ollama/deepseek-r1:14b",
        base_url: str = "http://localhost:11434",
        max_depth: int = 2,
        max_sub_questions: int = 5,
        provider: str = "ollama",
        cost_service: Any = None,  # CostService from core.cost
    ):
        self.max_depth = max_depth
        self.max_sub_questions = max_sub_questions
        self.base_url = base_url
        self.provider = provider
        self._cost_service = cost_service
        self._cache_enabled = cost_service is not None
        self._tool_descriptions: str | None = None  # lazy-built
        _ensure_crewai()  # Load crewAI classes if not already loaded

        if provider == "deepseek":
            # Cloud DeepSeek API (OpenAI-compatible, fast, no GPU needed)
            # NOTE: DeepSeek does NOT support structured output (response_format).
            # Set response_format=None to prevent crewAI from using beta.chat.completions.parse().
            from ai_workspace.providers import ProviderRegistry
            registry = ProviderRegistry()
            ds = registry.providers.get("deepseek")
            if not ds:
                raise ValueError("DeepSeek API not configured. Set DEEPSEEK_API_KEY env.")

            self.llm = _LLM(
                model="deepseek-chat",
                base_url=ds.base_url,
                api_key=ds.api_key,
                response_format=None,  # DeepSeek doesn't support structured output
            )
            self.deep_llm = _LLM(
                model="deepseek-reasoner",
                base_url=ds.base_url,
                api_key=ds.api_key,
                response_format=None,  # DeepSeek doesn't support structured output
            )
        else:
            # Local Ollama
            ollama_api_url = base_url  # http://localhost:11434 (no /v1, raw API for LiteLLM)
            fast_model = model.split("/")[-1] if "/" in model else model
            reasoning_model = deep_model.split("/")[-1] if "/" in deep_model else deep_model

            self.llm = _LLM(
                model=fast_model,
                base_url=ollama_api_url,
                api_key="ollama",
                provider="ollama",
            )
            self.deep_llm = _LLM(
                model=reasoning_model,
                base_url=ollama_api_url,
                api_key="ollama",
                provider="ollama",
            )

    async def _cached_kickoff(
        self, prompt: str, crew: Crew, task_type: str, model_name: str,
        output_model: type | None = None,
        provider: str = "deepseek",
    ) -> tuple:
        """Run crew.kickoff_async() with semantic cache + budget enforcement.

        crewAI 1.x requires kickoff_async() when called from async context.

        Args:
            output_model: Optional Pydantic model for output_pydantic tasks.
            provider: Provider name for budget tracking (default: deepseek).

        Returns (result, was_cache_hit). Result is either str or Pydantic model.

        Raises:
            BudgetExceededError: If the call would exceed budget limits.
        """
        import time as _time

        from ai_workspace.core.cost import BudgetExceededError

        if not self._cache_enabled:
            result = await crew.kickoff_async()
            if output_model is not None and hasattr(result, 'pydantic'):
                return result.pydantic, False
            return str(result), False

        # 1. Check cache
        cached = self._cost_service.cache.get(prompt, task_type)
        if cached:
            import logging
            logging.getLogger("aiw.cost").debug(
                "Cache HIT type=%s similarity=%.2f", task_type, cached["similarity"]
            )
            self._cost_service.budget.record_success(
                provider=provider,
                model=model_name,
                task_type=task_type,
                input_tokens=0,
                output_tokens=0,
                cost=0.0,
                cache_hit=True,
            )
            cached_text = cached["response_text"]
            if output_model is not None:
                return output_model.model_validate_json(cached_text), True
            return cached_text, True

        # 2. Budget check — use router to estimate cost correctly per provider
        len(prompt) // 4 + 500  # rough: prompt + ~500 output
        est_cost = self._estimate_llm_cost(prompt, provider, model_name)
        allowed, reason = self._cost_service.budget.can_call(est_cost, provider)
        if not allowed:
            raise BudgetExceededError(
                f"Budget blocked: {reason}. "
                f"Daily: ${self._cost_service.budget.today_spent():.4f}/"
                f"${self._cost_service.budget.DAILY_BUDGET:.2f}"
            )

        # 3. Cache miss — run LLM
        start = _time.monotonic()
        try:
            result = await crew.kickoff_async()
            # Extract Pydantic model if available, else get string
            if output_model is not None and hasattr(result, 'pydantic'):
                result_data = result.pydantic
                result_text = result_data.model_dump_json()
            else:
                result_data = str(result)
                result_text = result_data
            duration_ms = int((_time.monotonic() - start) * 1000)

            # Accurate cost estimation using router
            est_input = len(prompt) // 4
            est_output = len(result_text) // 4
            est_cost = self._estimate_llm_cost(prompt, provider, model_name)

            # 4. Store in cache
            self._cost_service.cache.set(
                prompt, result_text, task_type, model_name,
                tokens_used=est_input + est_output, cost=est_cost
            )

            # 5. Log cost via budget enforcer
            self._cost_service.budget.record_success(
                provider=provider,
                model=model_name,
                task_type=task_type,
                input_tokens=est_input,
                output_tokens=est_output,
                cost=est_cost,
                cache_hit=False,
                duration_ms=duration_ms,
            )

            return result_data, False
        except Exception as e:
            duration_ms = int((_time.monotonic() - start) * 1000)
            self._cost_service.budget.record_failure(
                provider=provider,
                model=model_name,
                task_type=task_type,
                error=str(e)[:200],
                duration_ms=duration_ms,
            )
            raise

    @staticmethod
    def _estimate_llm_cost(prompt: str, provider: str, model: str) -> float:
        """Estimate cost for an LLM call using the SmartRouter."""
        try:
            from ai_workspace.agents.router import get_router
            router = get_router()
            model_info = router._find_model(provider, model)
            if model_info and model_info.cost_per_1k_tokens > 0:
                est_input = max(100, len(prompt) // 4)
                est_output = est_input // 2
                return round(
                    model_info.cost_per_1k_input * (est_input / 1000)
                    + model_info.cost_per_1k_output * (est_output / 1000),
                    6,
                )
        except Exception:
            pass
        # Fallback: free (Ollama) or ~$0.00014/1k (DeepSeek)
        return 0.0

    def _create_planner_agent(self) -> Agent:
        """Agent that breaks down a query into sub-questions."""
        return _Agent(
            role="Senior Research Planner",
            goal="Break down research questions into specific, answerable sub-questions",
            backstory=(
                "You are an expert research planner. For any research question, "
                "you create a tree of sub-questions that, when answered, will "
                "provide a comprehensive understanding of the topic. Focus on "
                "diverse angles: technical, practical, comparative, historical."
            ),
            llm=self.llm,
            verbose=False,
        )

    def _create_researcher_agent(self) -> Agent:
        """Agent that answers individual sub-questions."""
        try:
            from ai_workspace.tools import (
                Crawl4AITool,
                HeadlessBrowserTool,
                MercadoLivreSearchTool,
                OLXSearchTool,
                PaginatedScraperTool,
                WebFetchTool,
            )
            tools = [
                Crawl4AITool(),          # Primary: LLM-friendly markdown, JS rendering
                WebFetchTool(),           # Fallback: static HTML
                HeadlessBrowserTool(),    # Fallback: complex SPAs
                PaginatedScraperTool(),   # Multi-page tables
                MercadoLivreSearchTool(), # BR marketplace
                OLXSearchTool(),          # BR classifieds
            ]
            tool_descriptions = (
                "Available tools (try in order):\n"
                "- crawl4ai_scrape: PRIMARY scraper. Returns clean markdown from any URL. "
                "Handles JavaScript, produces LLM-optimized output. Use this first.\n"
                "- web_fetch: reads static HTML pages and APIs (fallback)\n"
                "- headless_browser: renders JavaScript SPA pages in a real browser\n"
                "- paginated_scraper: navigates multi-page tables\n"
                "- mercado_livre_search / olx_search: BR marketplace prices\n"
            )
        except ImportError:
            tools = []
            tool_descriptions = "No web tools available. Use your training knowledge."

        # Cache for reuse in _answer_sub_question
        self._tool_descriptions = tool_descriptions

        return _Agent(
            role="Research Analyst",
            goal="Answer research questions thoroughly using web tools for real data",
            backstory=(
                "You are a diligent research analyst. You provide accurate, "
                "well-structured answers to specific questions. Always cite "
                "your reasoning and note any uncertainty. "
                "CRITICAL: Never invent data. If tools fail, report the failure honestly.\n"
                + tool_descriptions +
                "\nFor SPA/Angular pages that web_fetch can't read, use crawl4ai_scrape. "
                "For multi-page lists, use paginated_scraper with appropriate max_pages. "
                "Always try crawl4ai_scrape first — it produces the best markdown."
            ),
            llm=self.deep_llm,
            tools=tools,
            verbose=False,
        )

    def _create_synthesizer_agent(self) -> Agent:
        """Agent that synthesizes all findings into a report."""
        return _Agent(
            role="Research Synthesizer",
            goal="Synthesize multiple research findings into a cohesive report",
            backstory=(
                "You are a skilled writer and analyst. You take multiple "
                "research findings and weave them into a clear, comprehensive "
                "report with key takeaways, detailed analysis, and citations."
            ),
            llm=self.llm,
            verbose=False,
            max_retry_limit=2,
        )

    def _create_supervisor_agent(self) -> Agent:
        """Agent that oversees research — decides if sub-questions are adequate."""
        return _Agent(
            role="Research Supervisor",
            goal=(
                "Ensure the research plan covers all angles with the right depth. "
                "Remove redundant sub-questions. Add missing perspectives. "
                "Decide when research is deep enough to synthesize."
            ),
            backstory=(
                "You are a senior research director. You review research plans "
                "and decide: approve for execution, trim duplicates, or request "
                "additional angles. You optimize for depth vs breadth — fewer "
                "well-researched answers beat many shallow ones."
            ),
            llm=self.llm,
            verbose=False,
        )

    def _create_critic_agent(self) -> Agent:
        """Agent that reviews report quality — can trigger revision."""
        return _Agent(
            role="Research Critic",
            goal=(
                "Critically review research reports for quality, accuracy, "
                "and completeness. Identify gaps, unsupported claims, or "
                "areas needing deeper investigation."
            ),
            backstory=(
                "You are a rigorous peer reviewer. You examine research reports "
                "and decide: APPROVE (ready), REVISE (specific improvements needed), "
                "or REJECT (fundamental issues, needs re-research). Be specific "
                "about what needs improvement."
            ),
            llm=self.llm,
            verbose=False,
        )

    async def _kimi_web_search(self, query: str) -> list[dict[str, str]]:
        """Use Kimi Moonshot Search for web results (if configured)."""
        # Kimi uses MCP for search - this is a simplified HTTP fallback
        # In production, you'd use the MCP client
        try:
            async with httpx.AsyncClient():
                # Placeholder: actual Kimi search via MCP or API
                # Config is in ~/.kimi/config.toml
                return []
        except Exception:
            return []

    async def _answer_sub_question(
        self, sq: SubQuestion, depth: int = 0
    ) -> SubQuestion:
        """Answer a single sub-question, potentially recursing deeper."""

        researcher = self._create_researcher_agent()

        task = _Task(
            description=(
                f"Research question: {sq.question}\n"
                f"Context from parent: {sq.context}\n\n"
                + (self._tool_descriptions or "") +
                "\nIMPORTANT: Use crawl4ai_scrape first for any URL. It returns clean markdown.\n"
                "For lists spanning multiple pages, use paginated_scraper to get all data.\n"
                "USE THE TOOLS to get real data. Don't guess from training data.\n\n"
                "Provide a thorough answer. If the topic is complex, "
                "identify 2-3 further sub-questions that need investigation."
            ),
            expected_output="A structured research answer with confidence score",
            output_pydantic=ResearchAnswer if self.provider != "deepseek" else None,
            output_json=None,  # DeepSeek doesn't support structured output
            agent=researcher,
            guardrail=lambda o: guardrail_min_confidence(o, 0.3),
            guardrail_max_retries=2,
        )

        crew = _Crew(agents=[researcher], tasks=[task], verbose=False)
        result, was_cached = await self._cached_kickoff(
            task.description, crew, "research",
            "deepseek-reasoner" if self.provider == "deepseek" else self.deep_llm.model,
            output_model=ResearchAnswer if self.provider != "deepseek" else None,
        )

        if isinstance(result, ResearchAnswer):
            sq.answer = result.answer
            sq.sources = result.sources
            sq.confidence = result.confidence
            # Recurse if deeper questions found
            further = result.further_questions
            if depth < self.max_depth and further:
                for fq in further[: self.max_sub_questions]:
                    child = SubQuestion(question=fq, context=sq.answer)
                    child = await self._answer_sub_question(child, depth + 1)
        else:
            # Fallback: parse string manually
            try:
                data = json.loads(str(result))
                sq.answer = data.get("answer", str(result))
                sq.sources = data.get("sources", [])
                sq.confidence = _safe_float(data.get("confidence", 0.5), 0.5)
            except (json.JSONDecodeError, TypeError):
                sq.answer = str(result)
                sq.confidence = 0.5

        return sq

    async def research(
        self, query: str, progress: Callable | None = None,
        *, human_review: bool = False,
    ) -> ResearchResult:
        """Main entry point: research a query deeply.

        Args:
            query: The research question
            progress: Optional callback(dict) for real-time progress updates.
                      Keys: phase, detail, status, total, current
            human_review: If True, pauses before returning for user approval
        """
        def report(phase, detail, status="running", **kw):
            if progress:
                progress({"phase": phase, "detail": detail, "status": status, **kw})

        result = ResearchResult(original_query=query)

        # Step 1: Plan - break into sub-questions
        report("planning", "Generating research plan...")

        planner = self._create_planner_agent()
        plan_task = _Task(
            description=(
                f"Research query: {query}\n\n"
                f"Generate {self.max_sub_questions} specific sub-questions that "
                f"will provide comprehensive coverage of this topic. "
                f"Include diverse angles: fundamentals, advanced, practical, comparative."
            ),
            expected_output="A list of specific research sub-questions",
            output_pydantic=PlanOutput if self.provider != "deepseek" else None,
            output_json=None,  # DeepSeek doesn't support structured output
            agent=planner,
        )

        plan_crew = _Crew(agents=[planner], tasks=[plan_task], verbose=False)
        plan_result, _ = await self._cached_kickoff(
            plan_task.description, plan_crew, "research",
            "deepseek-chat" if self.provider == "deepseek" else self.llm.model,
            output_model=PlanOutput if self.provider != "deepseek" else None,
        )

        # plan_result is a PlanOutput Pydantic model (or fallback string)
        if isinstance(plan_result, PlanOutput):
            sub_qs = plan_result.questions
        else:
            # Fallback for cache hits or legacy: parse string
            try:
                sub_qs = _parse_json_safe(str(plan_result))
                if isinstance(sub_qs, dict):
                    sub_qs = sub_qs.get("questions", sub_qs.get("sub_questions", []))
            except (ValueError, json.JSONDecodeError, TypeError):
                sub_qs = [
                    q.strip().lstrip("0123456789. -")
                    for q in str(plan_result).split("\n")
                    if q.strip() and not q.strip().startswith(("```", "[", "]", "{", "}"))
                    and len(q.strip()) > 15
                ][:self.max_sub_questions]

        if not sub_qs:
            sub_qs = [query]

        total = min(len(sub_qs), self.max_sub_questions)
        report("planning", f"Plan: {total} sub-questions to research", "done", total=total)
        for i, q in enumerate(sub_qs[:total]):
            report("planning", f"  {i+1}. {q[:100]}", "info")

        # Step 1.5: Supervisor — review and refine the plan
        report("supervising", "Supervisor reviewing research plan...")
        try:
            supervisor = self._create_supervisor_agent()
            sup_task = _Task(
                description=(
                    f"Original query: {query}\n\n"
                    f"Proposed sub-questions:\n" +
                    "\n".join(f"{i+1}. {q}" for i, q in enumerate(sub_qs[:total])) +
                    "\n\nReview this plan. Are the sub-questions well-scoped? "
                    "Any duplicates? Any missing angles? "
                    "Respond ONLY with a numbered list of the FINAL sub-questions "
                    "(max {self.max_sub_questions}). Trim or add as needed."
                ),
                expected_output="A refined list of research sub-questions",
                agent=supervisor,
            )
            sup_crew = _Crew(agents=[supervisor], tasks=[sup_task], verbose=False)
            sup_result = await sup_crew.kickoff_async()
            # Parse supervisor output — extract numbered questions
            refined = [
                q.strip().lstrip("0123456789. -")
                for q in str(sup_result).split("\n")
                if q.strip() and len(q.strip()) > 15
                and not q.strip().startswith(("```", "[", "]", "{", "}", "#"))
            ][:self.max_sub_questions]
            if refined and len(refined) >= 2:
                old_total = total
                sub_qs = refined
                total = min(len(refined), self.max_sub_questions)
                report("supervising",
                    f"Supervisor refined: {old_total} → {total} sub-questions",
                    "done", total=total)
                for i, q in enumerate(sub_qs[:total]):
                    report("supervising", f"  {i+1}. {q[:100]}", "info")
            else:
                report("supervising", "Supervisor accepted plan as-is", "done")
        except Exception as e:
            logger.debug("Supervisor step skipped: %s", e)
            report("supervising", "Supervisor unavailable — using original plan", "done")

        # Step 2: Research each sub-question
        sub_questions = []
        for i, q in enumerate(sub_qs[:total]):
            report("researching", f"[{i+1}/{total}] {q[:80]}...", current=i+1, total=total)
            sq = SubQuestion(question=q, context=query)
            sq = await self._answer_sub_question(sq)
            sub_questions.append(sq)
            report("researching", f"[{i+1}/{total}] Done (confidence: {sq.confidence:.0%})", "done", current=i+1, total=total)

        result.sub_questions = sub_questions

        # Step 2.5: Source reputation — filter low-quality sources
        report("filtering", "Checking source credibility...")
        all_sources: list[str] = []
        for sq in sub_questions:
            all_sources.extend(sq.sources)
        if all_sources:
            try:
                from ai_workspace.sources import SourceReputationService
                src_svc = SourceReputationService()
                src_svc.initialize()
                trusted, ignored = src_svc.filter_sources(list(set(all_sources)))
                # Record source usage
                for url in all_sources:
                    try:
                        src_svc.record_use(url)
                    except Exception:
                        pass
                if ignored:
                    ignored_domains = [i["domain"] for i in ignored[:5]]
                    report("filtering",
                        f"Ignored {len(ignored)} sources (low credibility): {', '.join(ignored_domains)}",
                        "info")
                    # Add source quality note to findings
                    findings = "\n\n".join(
                        f"Q: {sq.question}\nA: {sq.answer}\nConfidence: {sq.confidence}"
                        f"\n Note: {len(ignored)} sources were filtered for low credibility."
                        if sq == sub_questions[0] else
                        f"Q: {sq.question}\nA: {sq.answer}\nConfidence: {sq.confidence}"
                        for sq in sub_questions
                    )
                    report("filtering", f"Trusted: {len(trusted)} sources", "done")
                # Log cross-reference: group sources by domain for scoring
                if trusted and len(trusted) >= 2:
                    try:
                        # Build simple claims from sub-questions and their sources
                        claims = []
                        for sq in sub_questions:
                            if sq.sources:
                                claims.append({
                                    "claim": sq.question[:200],
                                    "sources_agreeing": sq.sources[:5],
                                    "sources_disagreeing": [],
                                })
                        if claims:
                            src_svc.log_cross_reference(None, claims)
                    except Exception:
                        pass
            except Exception as e:
                logger.debug("Source filtering skipped: %s", e)

        # Step 3: Synthesize into report
        report("synthesizing", "Synthesizing final report...")

        synthesizer = self._create_synthesizer_agent()
        findings = "\n\n".join(
            f"Q: {sq.question}\nA: {sq.answer}\nConfidence: {sq.confidence}"
            for sq in sub_questions
        )

        synth_task = _Task(
            description=(
                f"Original research question: {query}\n\n"
                f"Research findings:\n{findings}\n\n"
                f"Synthesize these findings into a comprehensive report with:\n"
                f"1. Executive summary (2-3 sentences)\n"
                f"2. Key findings (bullet points)\n"
                f"3. Detailed analysis (full text)\n"
                f"4. Confidence assessment\n"
                f"5. All sources used"
            ),
            expected_output="A structured research report",
            output_pydantic=SynthesisReport if self.provider != "deepseek" else None,
            output_json=None,  # DeepSeek doesn't support structured output
            agent=synthesizer,
            guardrail=lambda o: guardrail_min_confidence(o, 0.4),
            guardrail_max_retries=2,
        )

        synth_crew = _Crew(agents=[synthesizer], tasks=[synth_task], verbose=False)
        synth_result, _ = await self._cached_kickoff(
            synth_task.description, synth_crew, "research",
            "deepseek-chat" if self.provider == "deepseek" else self.llm.model,
            output_model=SynthesisReport if self.provider != "deepseek" else None,
        )

        if isinstance(synth_result, SynthesisReport):
            result.summary = synth_result.summary
            result.detailed_report = (
                "## Key Findings\n\n" +
                "\n".join(f"- {kf}" for kf in synth_result.key_findings) +
                "\n\n## Detailed Analysis\n\n" +
                synth_result.detailed_analysis
            )
            result.sources = synth_result.sources
            result.confidence = synth_result.confidence
        else:
            # Fallback: parse string manually
            try:
                report_data = json.loads(str(synth_result))
                result.summary = report_data.get("summary", "")
                result.detailed_report = report_data.get("detailed_analysis", str(synth_result))
                result.sources = report_data.get("sources", [])
                result.confidence = _safe_float(report_data.get("confidence", 0.5), 0.5)
            except (json.JSONDecodeError, TypeError):
                result.detailed_report = str(synth_result)

        report("synthesizing", "Report complete", "done")

        # Step 4: Critic — review quality, may trigger revision
        report("reviewing", "Critic reviewing report quality...")
        revision_count = 0
        MAX_REVISIONS = 2
        while revision_count <= MAX_REVISIONS:
            try:
                critic = self._create_critic_agent()
                critic_task = _Task(
                    description=(
                        f"Original query: {query}\n\n"
                        f"Report to review:\n{result.detailed_report[:4000]}\n\n"
                        f"Confidence: {result.confidence:.0%}\n\n"
                        f"Review this report critically. Answer with ONLY one word:\n"
                        f"- APPROVE if the report is complete and accurate\n"
                        f"- REVISE if specific sections need improvement\n"
                        f"- REJECT if major issues require re-research\n"
                        f"If REVISE, add one line: what to improve."
                    ),
                    expected_output="APPROVE, REVISE, or REJECT (with reason if not APPROVE)",
                    agent=critic,
                )
                critic_crew = _Crew(agents=[critic], tasks=[critic_task], verbose=False)
                verdict = str(await critic_crew.kickoff_async()).strip().upper()

                if verdict.startswith("APPROVE"):
                    report("reviewing", "Critic: APPROVED ", "done")
                    break
                elif verdict.startswith("REVISE") and revision_count < MAX_REVISIONS:
                    revision_count += 1
                    reason = verdict.replace("REVISE", "").strip(":. -")
                    report("reviewing",
                        f"Critic: REVISE (attempt {revision_count}/{MAX_REVISIONS}) — {reason[:80]}",
                        "info")
                    # Re-synthesize with critic feedback
                    synth_task.description = (
                        synth_task.description +
                        f"\n\nCRITIC FEEDBACK: {reason}. Please improve the report addressing this."
                    )
                    synth_crew = _Crew(agents=[synthesizer], tasks=[synth_task], verbose=False)
                    synth_result, _ = await self._cached_kickoff(
                        synth_task.description, synth_crew, "research",
                        "deepseek-chat" if self.provider == "deepseek" else self.llm.model,
                        output_model=SynthesisReport if self.provider != "deepseek" else None,
                        provider="deepseek" if self.provider == "deepseek" else self.provider,
                    )
                    if isinstance(synth_result, SynthesisReport):
                        result.summary = synth_result.summary
                        result.detailed_report = (
                            "## Key Findings\n\n" +
                            "\n".join(f"- {kf}" for kf in synth_result.key_findings) +
                            "\n\n## Detailed Analysis\n\n" +
                            synth_result.detailed_analysis
                        )
                        result.sources = synth_result.sources
                        result.confidence = synth_result.confidence
                    else:
                        # Fallback: parse JSON string
                        try:
                            report_data = json.loads(str(synth_result))
                            result.summary = report_data.get("summary", result.summary)
                            result.confidence = _safe_float(report_data.get("confidence", result.confidence))
                        except (json.JSONDecodeError, TypeError):
                            pass
                else:
                    report("reviewing", f"Critic: {verdict[:80]}", "done")
                    break
            except Exception as e:
                logger.debug("Critic step skipped: %s", e)
                report("reviewing", "Critic unavailable — accepting report", "done")
                break

        # Step 5: Human-in-the-loop (if enabled)
        if human_review:
            report("reviewing", " Awaiting human review...", "info")
            if progress:
                progress({
                    "phase": "reviewing",
                    "detail": "Report ready for human review",
                    "status": "awaiting_approval",
                    "report": {
                        "summary": result.summary,
                        "confidence": result.confidence,
                        "sources": result.sources[:10],
                        "preview": result.detailed_report[:500],
                    },
                })

        return result


# Convenience function
async def deep_search(query: str, **kwargs) -> ResearchResult:
    """Run a deep search on a query."""
    engine = DeepSearchEngine(**kwargs)
    return await engine.research(query)
