"""
Deep Search Engine.

Implements recursive tree-based research:
1. Generate sub-questions from a query (planner)
2. For each sub-question: search web/local, summarize
3. Synthesize into final report

Supports:
- Ollama (deepseek-r1:14b, qwen3:14b) for reasoning
- Kimi Moonshot Search for web queries
- MCP servers as tools
"""

from __future__ import annotations

import asyncio
import json
from dataclasses import dataclass, field
from typing import Any, Callable

import httpx
from crewai import Agent, Crew, Task
from crewai.llm import LLM


@dataclass
class SubQuestion:
    """A sub-question generated by the planner."""
    question: str
    context: str = ""
    answer: str = ""
    sources: list[str] = field(default_factory=list)
    confidence: float = 0.0


@dataclass
class ResearchResult:
    """Complete research result."""
    original_query: str
    sub_questions: list[SubQuestion] = field(default_factory=list)
    summary: str = ""
    detailed_report: str = ""
    sources: list[str] = field(default_factory=list)
    confidence: float = 0.0


class DeepSearchEngine:
    """Recursive deep search using local LLMs + optional web search."""

    def __init__(
        self,
        model: str = "ollama/qwen3:14b",
        deep_model: str = "ollama/deepseek-r1:14b",
        base_url: str = "http://localhost:11434",
        max_depth: int = 2,
        max_sub_questions: int = 5,
        provider: str = "ollama",
    ):
        self.max_depth = max_depth
        self.max_sub_questions = max_sub_questions
        self.base_url = base_url
        
        if provider == "deepseek":
            # Cloud DeepSeek API (OpenAI-compatible, fast, no GPU needed)
            from ai_workspace.providers import ProviderRegistry
            registry = ProviderRegistry()
            ds = registry.providers.get("deepseek")
            if not ds:
                raise ValueError("DeepSeek API not configured. Set DEEPSEEK_API_KEY env.")
            
            self.llm = LLM(
                model="deepseek-chat",
                base_url=ds.base_url,
                api_key=ds.api_key,
            )
            self.deep_llm = LLM(
                model="deepseek-reasoner",
                base_url=ds.base_url,
                api_key=ds.api_key,
            )
        else:
            # Local Ollama
            ollama_api_url = base_url  # http://localhost:11434 (no /v1, raw API for LiteLLM)
            fast_model = model.split("/")[-1] if "/" in model else model
            reasoning_model = deep_model.split("/")[-1] if "/" in deep_model else deep_model

            self.llm = LLM(
                model=fast_model,
                base_url=ollama_api_url,
                api_key="ollama",
                provider="ollama",
            )
            self.deep_llm = LLM(
                model=reasoning_model,
                base_url=ollama_api_url,
                api_key="ollama",
                provider="ollama",
            )

    def _create_planner_agent(self) -> Agent:
        """Agent that breaks down a query into sub-questions."""
        return Agent(
            role="Senior Research Planner",
            goal="Break down research questions into specific, answerable sub-questions",
            backstory=(
                "You are an expert research planner. For any research question, "
                "you create a tree of sub-questions that, when answered, will "
                "provide a comprehensive understanding of the topic. Focus on "
                "diverse angles: technical, practical, comparative, historical."
            ),
            llm=self.llm,
            verbose=False,
        )

    def _create_researcher_agent(self) -> Agent:
        """Agent that answers individual sub-questions."""
        return Agent(
            role="Research Analyst",
            goal="Answer research questions thoroughly using available knowledge",
            backstory=(
                "You are a diligent research analyst. You provide accurate, "
                "well-structured answers to specific questions. Always cite "
                "your reasoning and note any uncertainty."
            ),
            llm=self.deep_llm,
            verbose=False,
        )

    def _create_synthesizer_agent(self) -> Agent:
        """Agent that synthesizes all findings into a report."""
        return Agent(
            role="Research Synthesizer",
            goal="Synthesize multiple research findings into a cohesive report",
            backstory=(
                "You are a skilled writer and analyst. You take multiple "
                "research findings and weave them into a clear, comprehensive "
                "report with key takeaways, detailed analysis, and citations."
            ),
            llm=self.llm,
            verbose=False,
        )

    async def _kimi_web_search(self, query: str) -> list[dict[str, str]]:
        """Use Kimi Moonshot Search for web results (if configured)."""
        # Kimi uses MCP for search - this is a simplified HTTP fallback
        # In production, you'd use the MCP client
        try:
            async with httpx.AsyncClient() as client:
                # Placeholder: actual Kimi search via MCP or API
                # Config is in ~/.kimi/config.toml
                return []
        except Exception:
            return []

    async def _answer_sub_question(
        self, sq: SubQuestion, depth: int = 0
    ) -> SubQuestion:
        """Answer a single sub-question, potentially recursing deeper."""
        
        researcher = self._create_researcher_agent()
        
        task = Task(
            description=(
                f"Research question: {sq.question}\n"
                f"Context from parent: {sq.context}\n\n"
                f"Provide a thorough answer. If the topic is complex, "
                f"identify 2-3 further sub-questions that need investigation."
            ),
            expected_output=(
                "A JSON object with:\n"
                '- "answer": detailed answer to the question\n'
                '- "sources": list of reasoning sources (can be "internal knowledge")\n'
                '- "confidence": 0.0 to 1.0\n'
                '- "further_questions": list of strings (if deeper research needed)\n'
            ),
            agent=researcher,
        )

        crew = Crew(agents=[researcher], tasks=[task], verbose=False)
        result = crew.kickoff()

        # Parse result
        try:
            data = json.loads(str(result))
            sq.answer = data.get("answer", str(result))
            sq.sources = data.get("sources", [])
            sq.confidence = data.get("confidence", 0.5)
            
            # Recurse if deeper questions found
            further = data.get("further_questions", [])
            if depth < self.max_depth and further:
                for fq in further[: self.max_sub_questions]:
                    child = SubQuestion(question=fq, context=sq.answer)
                    child = await self._answer_sub_question(child, depth + 1)
                    # Don't nest deeply in the data model
                    
        except (json.JSONDecodeError, TypeError):
            sq.answer = str(result)
            sq.confidence = 0.5

        return sq

    async def research(self, query: str, progress: Callable | None = None) -> ResearchResult:
        """Main entry point: research a query deeply.
        
        Args:
            query: The research question
            progress: Optional callback(dict) for real-time progress updates.
                      Keys: phase, detail, status, total, current
        """
        def report(phase, detail, status="running", **kw):
            if progress:
                progress({"phase": phase, "detail": detail, "status": status, **kw})
        
        result = ResearchResult(original_query=query)

        # Step 1: Plan - break into sub-questions
        report("planning", "Generating research plan...")
        
        planner = self._create_planner_agent()
        plan_task = Task(
            description=(
                f"Research query: {query}\n\n"
                f"Generate {self.max_sub_questions} specific sub-questions that "
                f"will provide comprehensive coverage of this topic. "
                f"Include diverse angles: fundamentals, advanced, practical, comparative.\n\n"
                f"Return a JSON list of question strings."
            ),
            expected_output='JSON list of sub-questions: ["question 1", "question 2", ...]',
            agent=planner,
        )

        plan_crew = Crew(agents=[planner], tasks=[plan_task], verbose=False)
        plan_result = plan_crew.kickoff()

        # Parse sub-questions
        try:
            sub_qs = json.loads(str(plan_result))
            if isinstance(sub_qs, dict):
                sub_qs = sub_qs.get("questions", sub_qs.get("sub_questions", []))
        except (json.JSONDecodeError, TypeError):
            sub_qs = [
                q.strip().lstrip("0123456789. -")
                for q in str(plan_result).split("\n")
                if q.strip()
            ][:self.max_sub_questions]

        if not sub_qs:
            sub_qs = [query]

        total = min(len(sub_qs), self.max_sub_questions)
        report("planning", f"Plan: {total} sub-questions to research", "done", total=total)
        for i, q in enumerate(sub_qs[:total]):
            report("planning", f"  {i+1}. {q[:100]}", "info")

        # Step 2: Research each sub-question
        sub_questions = []
        for i, q in enumerate(sub_qs[:total]):
            report("researching", f"[{i+1}/{total}] {q[:80]}...", current=i+1, total=total)
            sq = SubQuestion(question=q, context=query)
            sq = await self._answer_sub_question(sq)
            sub_questions.append(sq)
            report("researching", f"[{i+1}/{total}] Done (confidence: {sq.confidence:.0%})", "done", current=i+1, total=total)

        result.sub_questions = sub_questions

        # Step 3: Synthesize into report
        report("synthesizing", "Synthesizing final report...")
        
        synthesizer = self._create_synthesizer_agent()
        findings = "\n\n".join(
            f"Q: {sq.question}\nA: {sq.answer}\nConfidence: {sq.confidence}"
            for sq in sub_questions
        )

        synth_task = Task(
            description=(
                f"Original research question: {query}\n\n"
                f"Research findings:\n{findings}\n\n"
                f"Synthesize these findings into a comprehensive report with:\n"
                f"1. Executive summary (2-3 sentences)\n"
                f"2. Key findings (bullet points)\n"
                f"3. Detailed analysis (full text)\n"
                f"4. Confidence assessment\n\n"
                f"Return as JSON with keys: summary, key_findings, detailed_analysis, "
                f"confidence, sources"
            ),
            expected_output="JSON report object",
            agent=synthesizer,
        )

        synth_crew = Crew(agents=[synthesizer], tasks=[synth_task], verbose=False)
        synth_result = synth_crew.kickoff()

        try:
            report_data = json.loads(str(synth_result))
            result.summary = report_data.get("summary", "")
            result.detailed_report = report_data.get("detailed_analysis", str(synth_result))
            result.sources = report_data.get("sources", [])
            result.confidence = report_data.get("confidence", 0.5)
        except (json.JSONDecodeError, TypeError):
            result.detailed_report = str(synth_result)

        report("synthesizing", "Report complete", "done")
        return result


# Convenience function
async def deep_search(query: str, **kwargs) -> ResearchResult:
    """Run a deep search on a query."""
    engine = DeepSearchEngine(**kwargs)
    return await engine.research(query)
